// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4bcFS-Mg9NHxoI-STkyFPPZLwohAn2ck',
    appId: '1:531685038148:web:e76dfed3355d376ce58411',
    messagingSenderId: '531685038148',
    projectId: 'loowuserapp',
    authDomain: 'loowuserapp.firebaseapp.com',
    storageBucket: 'loowuserapp.appspot.com',
    measurementId: 'G-WXFMY1NP1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiw8l73G5kmKSNHvN_H_94I8NjFOFKBqE',
    appId: '1:531685038148:android:077071d3cc0ad68ce58411',
    messagingSenderId: '531685038148',
    projectId: 'loowuserapp',
    storageBucket: 'loowuserapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFKduJV9mZVV8xqcfXBxGeQ3TMhv_E5V4',
    appId: '1:531685038148:ios:59db4c5af377a6fde58411',
    messagingSenderId: '531685038148',
    projectId: 'loowuserapp',
    storageBucket: 'loowuserapp.appspot.com',
    androidClientId: '531685038148-0dknobf7muhgu76vqbf7fo4scfs5vl7l.apps.googleusercontent.com',
    iosClientId: '531685038148-scuc0u7drs3jpa7ll3d4so5eteg70jo2.apps.googleusercontent.com',
    iosBundleId: 'com.example.webPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFKduJV9mZVV8xqcfXBxGeQ3TMhv_E5V4',
    appId: '1:531685038148:ios:59db4c5af377a6fde58411',
    messagingSenderId: '531685038148',
    projectId: 'loowuserapp',
    storageBucket: 'loowuserapp.appspot.com',
    androidClientId: '531685038148-0dknobf7muhgu76vqbf7fo4scfs5vl7l.apps.googleusercontent.com',
    iosClientId: '531685038148-scuc0u7drs3jpa7ll3d4so5eteg70jo2.apps.googleusercontent.com',
    iosBundleId: 'com.example.webPortal',
  );
}
